version: '3.8'

services:

  web:
    build: .
    ports:
      - 8080:8080
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8080
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A worker.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
      - /media/amari:/media/amari
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7
    ports:
      - 6379:6379
